---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: varshith10032003/calculator:latest
        source: pull

    - name: Running container
      shell: docker run -it -d --name calculator varshith10032003/calculator